### ISSUE TITLE
Should I change the repo name?

### ISSUE THREAD

**Issue by szpnygo** [metagogs/gogs#7]
gogs is a famous project name.

Should I change the repo name?

If you think the name should be changed, please give me some advice. or you think it's ok

**Comment by szpnygo** [comment]
I will confirm it before version 0.2.0, because maybe not many people will be using it at that time

**Comment by szpnygo** [comment]
BTW: I will complete version 0.2.0 before the end of November

**Comment by wuyiccc** [comment]
fork 楼主的仓库发现跟gogs重复了...
